import os
from dotenv import load_dotenv

load_dotenv()

EXCLUSIVE_TELEGRAM_BOT_TOKEN = os.getenv("EXCLUSIVE_TELEGRAM_BOT_TOKEN")
EXCLUSIVE_TELEGRAM_CHANNEL_ID = os.getenv("EXCLUSIVE_TELEGRAM_CHANNEL_ID")
EXCLUSIVE_INSTAGRAM_ACCESS_TOKEN = os.getenv("EXCLUSIVE_INSTAGRAM_ACCESS_TOKEN")
EXCLUSIVE_INSTAGRAM_ACCOUNT_ID = os.getenv("EXCLUSIVE_INSTAGRAM_ACCOUNT_ID")

STANDARD_TELEGRAM_BOT_TOKEN = os.getenv("STANDARD_TELEGRAM_BOT_TOKEN")
STANDARD_TELEGRAM_CHANNEL_ID = os.getenv("STANDARD_TELEGRAM_CHANNEL_ID")
STANDARD_INSTAGRAM_USERNAME = os.getenv("STANDARD_INSTAGRAM_USERNAME")
STANDARD_INSTAGRAM_PASSWORD = os.getenv("STANDARD_INSTAGRAM_PASSWORD")

USER_ID = int(os.getenv("MY_USER_ID"))
USER_AGENT = "Mozilla/5.0"